### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by UserBRMFC** [PizzaProgram/MCP23017-PCF8574-AIO#7]
I get an error when I try to load node @pizzaprogram/mcp-pcf-aio via manage pallete, this is the log  :

2022-11-03T12:22:30.070Z Install : @pizzaprogram/mcp-pcf-aio 2.3.8-20220907

2022-11-03T12:22:30.123Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict @pizzaprogram/mcp-pcf-aio@2.3.8-20220907
2022-11-03T12:22:31.767Z [err] npm
2022-11-03T12:22:31.769Z [err]  
2022-11-03T12:22:31.770Z [err] WARN
2022-11-03T12:22:31.770Z [err]  
2022-11-03T12:22:31.770Z [err] config
2022-11-03T12:22:31.770Z [err]  production Use `--omit=dev` instead.
2022-11-03T12:22:37.162Z [err] npm 
2022-11-03T12:22:37.163Z [err] ERR! 
2022-11-03T12:22:37.163Z [err] code 1
2022-11-03T12:22:37.164Z [err] npm ERR!
2022-11-03T12:22:37.164Z [err]  path
2022-11-03T12:22:37.165Z [err]  /config/node-red/node_modules/i2c-bus
2022-11-03T12:22:37.171Z [err] npm ERR!
2022-11-03T12:22:37.172Z [err]  command failed
2022-11-03T12:22:37.172Z [err] npm ERR! 
2022-11-03T12:22:37.172Z [err] command sh -c node-gyp rebuild
2022-11-03T12:22:37.172Z [err] npm ERR!
2022-11-03T12:22:37.173Z [err]  gyp info it worked if it ends with ok
2022-11-03T12:22:37.173Z [err] npm ERR!
2022-11-03T12:22:37.173Z [err]  gyp info using node-gyp@9.0.0
2022-11-03T12:22:37.173Z [err] npm ERR! gyp info using node@16.17.1 | linux | arm64
2022-11-03T12:22:37.173Z [err] npm ERR! gyp ERR! find Python 
2022-11-03T12:22:37.173Z [err] npm ERR!
2022-11-03T12:22:37.174Z [err]  gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2022-11-03T12:22:37.174Z [err] npm ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2022-11-03T12:22:37.174Z [err] npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2022-11-03T12:22:37.174Z [err] npm 
2022-11-03T12:22:37.174Z [err] ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2022-11-03T12:22:37.174Z [err] npm ERR!
2022-11-03T12:22:37.174Z [err]  gyp ERR! find Python checking if "python3" can be used
2022-11-03T12:22:37.174Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2022-11-03T12:22:37.174Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2022-11-03T12:22:37.174Z [err] npm 
2022-11-03T12:22:37.174Z [err] ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2022-11-03T12:22:37.174Z [err] npm ERR!
2022-11-03T12:22:37.175Z [err]  gyp ERR! find Python 
2022-11-03T12:22:37.175Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-11-03T12:22:37.175Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2022-11-03T12:22:37.175Z [err] npm ERR!
2022-11-03T12:22:37.175Z [err]  gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-11-03T12:22:37.175Z [err] npm ERR!
2022-11-03T12:22:37.175Z [err]  gyp ERR! find Python you can try one of the following options:
2022-11-03T12:22:37.175Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2022-11-03T12:22:37.175Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2022-11-03T12:22:37.175Z [err] npm 
2022-11-03T12:22:37.175Z [err] ERR! gyp ERR! find Python - Set the environment variable PYTHON
2022-11-03T12:22:37.175Z [err] npm ERR!
2022-11-03T12:22:37.175Z [err]  gyp ERR! find Python - Set the npm configuration variable python:
2022-11-03T12:22:37.175Z [err] npm ERR!
2022-11-03T12:22:37.175Z [err]  gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2022-11-03T12:22:37.175Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2022-11-03T12:22:37.176Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-11-03T12:22:37.176Z [err] npm 
2022-11-03T12:22:37.176Z [err] ERR! gyp ERR! find Python **********************************************************
2022-11-03T12:22:37.176Z [err] npm ERR!
2022-11-03T12:22:37.176Z [err]  gyp ERR! find Python 
2022-11-03T12:22:37.176Z [err] npm ERR!
2022-11-03T12:22:37.176Z [err]  gyp ERR! configure error 
2022-11-03T12:22:37.176Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2022-11-03T12:22:37.176Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2022-11-03T12:22:37.176Z [err] npm ERR!
2022-11-03T12:22:37.176Z [err]  gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2022-11-03T12:22:37.176Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2022-11-03T12:22:37.176Z [err] npm
2022-11-03T12:22:37.177Z [err]  ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2022-11-03T12:22:37.177Z [err] npm 
2022-11-03T12:22:37.177Z [err] ERR! gyp ERR! stack     at exithandler (node:child_process:408:5)
2022-11-03T12:22:37.177Z [err] npm ERR!
2022-11-03T12:22:37.177Z [err]  gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:420:5)
2022-11-03T12:22:37.177Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
2022-11-03T12:22:37.177Z [err] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
2022-11-03T12:22:37.177Z [err] npm
2022-11-03T12:22:37.177Z [err]  ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
2022-11-03T12:22:37.177Z [err] npm 
2022-11-03T12:22:37.177Z [err] ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-11-03T12:22:37.177Z [err] npm ERR!
2022-11-03T12:22:37.177Z [err]  gyp ERR! System Linux 5.15.61-v8
2022-11-03T12:22:37.177Z [err] npm ERR!
2022-11-03T12:22:37.177Z [err]  gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-11-03T12:22:37.177Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/i2c-bus
2022-11-03T12:22:37.178Z [err] npm ERR! gyp ERR! node -v v16.17.1
2022-11-03T12:22:37.178Z [err] npm 
2022-11-03T12:22:37.178Z [err] ERR! gyp ERR! node-gyp -v v9.0.0
2022-11-03T12:22:37.178Z [err] npm ERR!
2022-11-03T12:22:37.178Z [err]  gyp ERR! not ok
2022-11-03T12:22:37.185Z [err] 
2022-11-03T12:22:37.185Z [err] npm ERR! A complete log of this run can be found in:
2022-11-03T12:22:37.186Z [err] npm ERR!     /root/.npm/_logs/2022-11-03T12_22_31_618Z-debug-0.log
2022-11-03T12:22:37.206Z rc=1

**Comment by PizzaProgram** [comment]
Other users could install it without any problem.  
It seems that the "i2c" node (I'm calling as base of my node) could not be installed because of missing: python3 .  
But I'm not sure.  
I did not write the i2c node. You may ask the author... or check similar errors on that GitHub project. (See Readme for link)

PS: Please EDIT your comment and format the log as "code" !

**Comment by PizzaProgram** [comment]
What NodeRed version are you using?

**Comment by UserBRMFC** [comment]
Node Red v3.0.2 under Home assistant.
Which i2C node most i install ?

**Comment by PizzaProgram** [comment]
As I've already wrote above:
 i2c Link is on the MAIN page, called "link ... " . https://github.com/fivdi/i2c-bus
 - obviously you did not read what I've answered
 - you still did not format your log to code.

**Comment by UserBRMFC** [comment]
Sorry, I'm new to github, so what do you mean with ' format your log to code' ?
To install the node I have to type: 'npm install i2c bus' Where do I type this, I only know how to load nodes via the management palette in node red.

**Comment by PizzaProgram** [comment]
The right method to install **i2c** node-red package is:

1. You need to open a Terminal on your Linux machine. 
2. type or copy: `npm install i2c-bus`
3. press Enter, wait until it's finished
4. Restart node-red 

Are you sure you are using a Linux? Not a Windows?  
_(I've just tried to install to a Win7 32-bit PC, and saw similar errors. First I needed to install Python, but that was not enough either, because then the i2c-bus install complained about errors like: no "Visual Studio" is present ... )_

---

 I've just realized yesterday: 
## Made in 2022 a big mistake: 
 - did not upload my latest version [2.3.9.20220908] properly to here, nor to the NPM  ! :-1: 
 - the one uploaded [v2.3.8.20220907] does not work at all.

You should try this version, which is an enhanced one: 
https://flows.nodered.org/node/@joe-ab1do/mcp-pcf-aio

< OFF >
_PS: Sorry for the very late response. The last 14 month was a nightmare for me, could not work on this project._
